data:
  valid:
    module: torch.utils.data
    class: DataLoader
    DataLoader:
      dataset:
        module: datasets.NATCOM.dataset
        class: DocumentClassification
        DocumentClassification:
          datadirs:
            - '''/extdata/ocr/phungpx/projects/PHUNGPX/semantic_segmentation_pytorch/dataset/NATCOM2/valid/'''
            - '''dataset/multi_classes/document_classification/VEHICLE_REGISTRATION/valid/'''
          classes:
            CARD_BACK_TYPE_1: 0
            CARD_FRONT_TYPE_1: 1
            CARD_BACK_TYPE_2: 2
            CARD_FRONT_TYPE_2: 3
            CARD_BACK_TYPE_3: 4
            CARD_FRONT_TYPE_3: 5 
            PASSPORT: 6
            BLX: 7
            OTHERS: 8
          image_patterns: ['''*.*g''', '''*.*G''']
          image_size: (224, 224)
          inner_size: 256
      batch_size: 128
      pin_memory: True
      num_workers: 12
      drop_last: False
      shuffle: False

model:
  module: models.mobilenets
  class: MobileNetV3Small
  MobileNetV3Small:
    num_classes: 9
    pretrained: True
    
metrics:
  module: metrics.metrics
  class: Metric
  Metric:
    metric:
      accuracy:
        module: metrics.metric_funcs
        class: Accuracy
      loss:
        module: torch.nn
        class: CrossEntropyLoss
    output_transform: 'lambda x: (x[0], x[1])'

logger:
  module: handler.logger
  class: Logger
  Logger:
    log_mode: logging.DEBUG
    log_formatter: '''%(asctime)s - %(name)s - %(levelname)s - %(message)s'''

extralibs:
  torch: torch
  iaa: imgaug.augmenters
  logging: logging
  torchvision: torchvision
  transforms: torchvision.transforms